
--
CREATE DATABASE IF NOT EXISTS tabacaria;
USE tabacaria;

CREATE TABLE IF NOT EXISTS `cadasto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT DEFAULT NULL,
  `gmail` VARCHAR(100) DEFAULT NULL,
  `senha` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

